# Generated by Django 3.0 on 2019-12-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
