# Generated by Django 3.0 on 2019-12-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=12)),
                ('fname', models.CharField(max_length=12)),
                ('lname', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
