# Generated by Django 3.0 on 2019-12-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191223_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
