# Generated by Django 2.2 on 2019-12-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='signUp',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=12)),
                ('lname', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
