# Generated by Django 2.2 on 2019-12-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='uname',
            new_name='username',
        ),
    ]
